# Базовая конфигурация для работы с S3
endpoint_url: "https://s3.twcstorage.ru"
region: "ru-1"

# Бакеты по умолчанию для разных окружений
buckets:
  prod:
    source: "31d5eb06-file-storage"
    destination: "50dda1c9-test-copy"
  dev:
    source: "1be69fbc-file-storage"
    destination: "50c17271-check-copy"

# Настройки multipart загрузки
multipart:
  default_part_size_mb: 50
  max_part_size_mb: 100
  min_part_size_mb: 5
